# Generated by Django 3.0.4 on 2020-05-25 12:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardGrid',
            fields=[
                ('grid_layout', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='historicalStockData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
