# Generated by Django 3.0.4 on 2020-06-05 08:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('notes', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='stickyNote',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('notes', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
