# Generated by Django 3.0.4 on 2020-07-15 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tradingStrategyChoices',
            fields=[
                ('strategyChoice', models.CharField(default='None', max_length=25, primary_key=True, serialize=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='journalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('win', 'Win'), ('loss', 'Loss')], default='open', max_length=10)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('currency', models.CharField(blank=True, max_length=40, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=40)),
                ('strategy', models.CharField(blank=True, max_length=40, null=True)),
                ('position_opened', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('position_closed', models.DateTimeField(blank=True, null=True)),
                ('found_via', models.CharField(blank=True, max_length=50)),
                ('reason_bought', models.TextField(blank=True, null=True)),
                ('reason_sold', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='currenciesChoices',
            fields=[
                ('currency', models.CharField(default='None', max_length=4, primary_key=True, serialize=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
