# Generated by Django 3.0.4 on 2020-07-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='position_closed',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='position_opened',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reason_bought',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='reason_sold',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='side',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='size',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='status',
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='journalEntryTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryStopLosses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryScreenShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('action_type', models.CharField(choices=[('share', 'Share'), ('crypto', 'Crypto'), ('forex', 'Forex'), ('futures', 'Futures')], max_length=20)),
                ('reason_bought', models.TextField(blank=True, null=True)),
                ('reason_sold', models.TextField(blank=True, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('commision', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.journalEntry')),
            ],
        ),
    ]
