# Generated by Django 3.0.4 on 2020-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journaltargets',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='journaltargets',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='journalStopLosses',
        ),
    ]
