# Generated by Django 3.0.4 on 2020-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
