# Generated by Django 3.0.4 on 2020-09-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200831_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalscreenshots',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalscreenshots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
