# Generated by Django 3.0.4 on 2020-07-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20200723_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
