# Generated by Django 3.0.4 on 2020-07-30 12:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0006_auto_20200730_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='journalEntry',
            new_name='journal',
        ),
        migrations.RenameModel(
            old_name='journalEntryAction',
            new_name='journalAction',
        ),
        migrations.RenameModel(
            old_name='journalEntryScreenShots',
            new_name='journalScreenShots',
        ),
        migrations.RenameModel(
            old_name='journalEntryTargets',
            new_name='journalStopLosses',
        ),
        migrations.RenameModel(
            old_name='journalEntryStopLosses',
            new_name='journalTargets',
        ),
        migrations.RenameField(
            model_name='journalscreenshots',
            old_name='journalEntry',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='journalstoplosses',
            old_name='journalEntry',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='journalstoplosses',
            old_name='target_price',
            new_name='stop_loss',
        ),
        migrations.RenameField(
            model_name='journaltargets',
            old_name='journalEntry',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='journaltargets',
            old_name='stop_loss',
            new_name='target_price',
        ),
    ]
