# Generated by Django 3.0.4 on 2020-04-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stockTickers',
        ),
    ]
