# Generated by Django 3.0.4 on 2020-05-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20200510_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardgrid',
            old_name='gridLayout',
            new_name='grid_layout',
        ),
        migrations.AlterField(
            model_name='dashboardgrid',
            name='id',
            field=models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
