# Generated by Django 3.0.4 on 2020-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20200510_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardgrid',
            name='id',
        ),
        migrations.AlterField(
            model_name='dashboardgrid',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
