# Generated by Django 3.0.4 on 2020-05-25 09:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20200510_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='historicalStockData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
