# Generated by Django 3.0.4 on 2020-05-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_historicalstockdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dashboardGrid',
        ),
        migrations.DeleteModel(
            name='historicalStockData',
        ),
    ]
