# Generated by Django 3.0.4 on 2020-05-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20200530_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='currentUser',
            new_name='current_user',
        ),
    ]
