# Generated by Django 3.0.4 on 2020-07-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='journalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('share', 'Share'), ('crypto', 'Crypto'), ('forex', 'Forex'), ('futures', 'Futures')], default='share', max_length=20)),
                ('ticker', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('currency', models.CharField(blank=True, max_length=40, null=True)),
                ('strategy', models.CharField(blank=True, max_length=40, null=True)),
                ('found_via', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tradingStrategyChoices',
            fields=[
                ('strategyChoice', models.CharField(default='None', max_length=25, primary_key=True, serialize=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal-api.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryStopLosses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal-api.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryScreenShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal-api.journalEntry')),
            ],
        ),
        migrations.CreateModel(
            name='journalEntryAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('reason_bought', models.TextField(blank=True, null=True)),
                ('reason_sold', models.TextField(blank=True, null=True)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('commision', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal-api.journalEntry')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal-api.portfolio'),
        ),
        migrations.CreateModel(
            name='currenciesChoices',
            fields=[
                ('currency', models.CharField(default='None', max_length=4, primary_key=True, serialize=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
