# Generated by Django 3.0.4 on 2020-07-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal-api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='journalentryaction',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='journalentryscreenshots',
            name='journalEntry',
        ),
        migrations.RemoveField(
            model_name='journalentrystoplosses',
            name='journalEntry',
        ),
        migrations.RemoveField(
            model_name='journalentrytargets',
            name='journalEntry',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tradingstrategychoices',
            name='user',
        ),
        migrations.DeleteModel(
            name='currenciesChoices',
        ),
        migrations.DeleteModel(
            name='journalEntry',
        ),
        migrations.DeleteModel(
            name='journalEntryAction',
        ),
        migrations.DeleteModel(
            name='journalEntryScreenShots',
        ),
        migrations.DeleteModel(
            name='journalEntryStopLosses',
        ),
        migrations.DeleteModel(
            name='journalEntryTargets',
        ),
        migrations.DeleteModel(
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='tradingStrategyChoices',
        ),
    ]
