# Generated by Django 3.0.4 on 2020-08-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200808_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='time',
        ),
    ]
