# Generated by Django 3.0.4 on 2020-08-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20200809_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='Category',
        ),
    ]
