# Generated by Django 3.0.4 on 2020-08-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20200812_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='Category',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='expenses.Category'),
            preserve_default=False,
        ),
    ]
