# Generated by Django 3.0.4 on 2020-08-12 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0009_auto_20200812_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIncome',
            new_name='Income',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Category'),
        ),
    ]
