# Generated by Django 3.0.4 on 2020-05-10 07:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_company_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboardGrid',
            fields=[
                ('id', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('gridLayout', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
